select m.id, m.entity_type as entity, m.entity_id as id, u.phone_number as user_phone_number, m.channel, m.message_type, m.message_text from messages m inner join users u on m.recipient_id = u.id ;

Message.joins("inner join users u on messages.recipient_id = u.id").pluck("messages.id, messages.entity_type as 'Order/Shipment', messages.entity_id as id, u.phone_number as user_phone_number, messages.channel, messages.message_type, messages.message_text")


select messages.id as message_id, messages.entity_type as "Order/Shipment", messages.entity_id as "order/shipment id", messages.created_at,
u.phone_number as recipient_phone_number,
case
  when messages.channel = 0 then 'sms'
  when messages.channel = 1 then 'whatsapp'
  when messages.channel = 2 then 'voicecall'
  else null
end as channel,
case
  when messages.message_type = 0 then 'order_confirmation_with_surprise'
  when messages.message_type = 1 then 'order_confirmation_without_surprise'
  when messages.message_type = 2 then 'only_shipment_with_surprise_dispatched'
  when messages.message_type = 3 then 'only_shipment_without_surprise_dispatched'
  when messages.message_type = 4 then 'partial_shipment_with_surprise_dispatched'
  when messages.message_type = 5 then 'partial_shipment_without_surprise_dispatched'
  when messages.message_type = 6 then 'out_for_delivery'
  when messages.message_type = 7 then 'shipment_delivery_single_with_surprise'
  when messages.message_type = 8 then 'shipment_delivery_single_without_surprise'
  when messages.message_type = 9 then 'shipment_delivery_multiple_with_surprise'
  when messages.message_type = 10 then 'shipment_delivery_multiple_without_surprise'
  when messages.message_type = 11 then 'order_dispatch_delay'
  when messages.message_type = 12 then 'order_delivery_delay'
  when messages.message_type = 13 then 'order_watch_videos'
  when messages.message_type = 14 then 'order_item_cancellation_support'
  when messages.message_type = 15 then 'order_cancellation_customer'
  when messages.message_type = 16 then 'payment_refund'
  when messages.message_type = 17 then 'delayed_shipment_delivery'
  when messages.message_type = 18 then 'delayed_shipment_delivery_last'
  when messages.message_type = 19 then 'early_delivery'
  when messages.message_type = 20 then 'bag_abandon'
  when messages.message_type = 21 then 'order_payment_failure'
  when messages.message_type = 22 then 'welcome_message'
  when messages.message_type = 23 then 'order_confirmation_with_surprise_upgrade_to_prepaid'
  when messages.message_type = 24 then 'essential_products_order_confirmation'
  else null 
end as message_type,
messages.message_text
from messages
inner join users u on messages.recipient_id = u.id
order by messages.created_at desc

-----
SQL command is: PGPASSWORD=fam0usf0xy psql -h foxy-prod.crpdkkpcpspo.ap-south-1.rds.amazonaws.com -U foxy -d foxy_api_production -c "\COPY ( SELECT sku.id AS \"Product Code\", ROUND((((100 - COALESCE( ai1.margin_percent, ai.margin_percent)) * p.mrp)/100)/(1 + hm.gst_rate/100.0), 2) AS \"Vendor Price\", o.organisation_code AS \"Vendor Code\", COALESCE(p.brand_ean, p.brand_sku, sku.id::text) AS \"Vendor SkuCode\", NULL AS Inventory, 1 AS Priority, 'Yes' AS Enabled FROM skus sku LEFT JOIN products p ON sku.item_type = 'Product' AND sku.item_id = p.id LEFT JOIN brands b ON p.brand_id = b.id LEFT JOIN assortment_inputs ai ON ai.brand_id = b.id AND ai.fulfillment_model = 0 AND ai.product_id is null AND ai.variant_id is null LEFT JOIN assortment_inputs ai1 ON ai1.brand_id = b.id AND p.id = ai1.product_id AND ai1.variant_id is null INNER JOIN organisation_to_brands ob ON ob.brand_id = b.id INNER JOIN organisations o ON ob.organisation_id = o.id LEFT JOIN hsn_mappings hm ON hm.hsn_code = regexp_replace(p.hsn_code, '\.', '', 'g') WHERE p.priority IN ('Priority SKU', 'Single Stock') AND (p.variants_count is null or p.variants_count = 0) AND p.deleted_at IS NULL UNION SELECT sku.id AS \"Product Code\", ROUND((((100 - COALESCE( ai2.margin_percent, ai1.margin_percent, ai.margin_percent)) * v.mrp)/100)/(1 + hm.gst_rate/100.0), 2) AS \"Vendor Price\", o.organisation_code AS \"Vendor Code\", COALESCE(v.brand_ean, v.brand_sku, sku.id::text) AS \"Vendor SkuCode\", NULL AS Inventory, 1 AS Priority, 'Yes' AS Enabled FROM skus sku LEFT JOIN variants v ON sku.item_type = 'Variant' and sku.item_id = v.id INNER JOIN products p ON v.product_id = p.id LEFT JOIN brands b ON p.brand_id = b.id LEFT JOIN assortment_inputs ai ON ai.brand_id = b.id AND ai.fulfillment_model = 0 AND ai.product_id is null AND ai.variant_id is null LEFT JOIN assortment_inputs ai1 ON ai1.brand_id = b.id and p.id = ai1.product_id and ai1.variant_id is null LEFT JOIN assortment_inputs ai2 ON ai2.variant_id = v.id INNER JOIN organisation_to_brands ob ON ob.brand_id = b.id INNER JOIN organisations o ON ob.organisation_id = o.id LEFT JOIN hsn_mappings hm on hm.hsn_code = regexp_replace(v.hsn_code, '\.', '', 'g') WHERE v.priority IN ('Priority SKU', 'Single Stock') AND v.deleted_at IS NULL ORDER BY \"Vendor SkuCode\" ) TO '/home/ubuntu/wms/public/Vendor-ItemMaster-2020-Jul-03-15-46-58.csv' WITH (FORMAT CSV, header, FORCE_QUOTE *)" 2>&1


----
SQL command is: PGPASSWORD=fam0usf0xy psql -h foxy-prod.crpdkkpcpspo.ap-south-1.rds.amazonaws.com -U foxy -d foxy_api_production -c "\COPY ( SELECT messages.id as message_id, messages.entity_type as "Order/Shipment", messages.entity_id as "Order/Shipment ID", messages.created_at, u.phone_number as recipient_phone_number, case when messages.channel = 0 then 'sms' when messages.channel = 1 then 'whatsapp' when messages.channel = 2 then 'voicecall' else null end as channel, case when messages.message_type = 0 then 'order_confirmation_with_surprise' when messages.message_type = 1 then 'order_confirmation_without_surprise' when messages.message_type = 2 then 'only_shipment_with_surprise_dispatched' when messages.message_type = 3 then 'only_shipment_without_surprise_dispatched' when messages.message_type = 4 then 'partial_shipment_with_surprise_dispatched' when messages.message_type = 5 then 'partial_shipment_without_surprise_dispatched' when messages.message_type = 6 then 'out_for_delivery' when messages.message_type = 7 then 'shipment_delivery_single_with_surprise' when messages.message_type = 8 then 'shipment_delivery_single_without_surprise' when messages.message_type = 9 then 'shipment_delivery_multiple_with_surprise' when messages.message_type = 10 then 'shipment_delivery_multiple_without_surprise' when messages.message_type = 11 then 'order_dispatch_delay' when messages.message_type = 12 then 'order_delivery_delay' when messages.message_type = 13 then 'order_watch_videos' when messages.message_type = 14 then 'order_item_cancellation_support' when messages.message_type = 15 then 'order_cancellation_customer' when messages.message_type = 16 then 'payment_refund' when messages.message_type = 17 then 'delayed_shipment_delivery' when messages.message_type = 18 then 'delayed_shipment_delivery_last' when messages.message_type = 19 then 'early_delivery' when messages.message_type = 20 then 'bag_abandon' when messages.message_type = 21 then 'order_payment_failure' when messages.message_type = 22 then 'welcome_message' when messages.message_type = 23 then 'order_confirmation_with_surprise_upgrade_to_prepaid' when messages.message_type = 24 then 'essential_products_order_confirmation' else null end as message_type, messages.message_text from messages inner join users u on messages.recipient_id = u.id order by messages.created_at desc ) TO '/home/ubuntu/wms/public/messages.csv' WITH (FORMAT CSV, header, FORCE_QUOTE *)" 2>&1

SQL command is: PGPASSWORD=fam0usf0xy psql -h foxy-prod.crpdkkpcpspo.ap-south-1.rds.amazonaws.com -U foxy -d foxy_api_production -c "\COPY ( SELECT messages.id as message_id, messages.entity_type as "Order-Shipment", messages.entity_id as "Order-Shipment ID", messages.created_at, u.phone_number as recipient_phone_number, case when messages.channel = 0 then 'sms' when messages.channel = 1 then 'whatsapp' when messages.channel = 2 then 'voicecall' else null end as channel, case when messages.message_type = 0 then 'order_confirmation_with_surprise' when messages.message_type = 1 then 'order_confirmation_without_surprise' when messages.message_type = 2 then 'only_shipment_with_surprise_dispatched' when messages.message_type = 3 then 'only_shipment_without_surprise_dispatched' when messages.message_type = 4 then 'partial_shipment_with_surprise_dispatched' when messages.message_type = 5 then 'partial_shipment_without_surprise_dispatched' when messages.message_type = 6 then 'out_for_delivery' when messages.message_type = 7 then 'shipment_delivery_single_with_surprise' when messages.message_type = 8 then 'shipment_delivery_single_without_surprise' when messages.message_type = 9 then 'shipment_delivery_multiple_with_surprise' when messages.message_type = 10 then 'shipment_delivery_multiple_without_surprise' when messages.message_type = 11 then 'order_dispatch_delay' when messages.message_type = 12 then 'order_delivery_delay' when messages.message_type = 13 then 'order_watch_videos' when messages.message_type = 14 then 'order_item_cancellation_support' when messages.message_type = 15 then 'order_cancellation_customer' when messages.message_type = 16 then 'payment_refund' when messages.message_type = 17 then 'delayed_shipment_delivery' when messages.message_type = 18 then 'delayed_shipment_delivery_last' when messages.message_type = 19 then 'early_delivery' when messages.message_type = 20 then 'bag_abandon' when messages.message_type = 21 then 'order_payment_failure' when messages.message_type = 22 then 'welcome_message' when messages.message_type = 23 then 'order_confirmation_with_surprise_upgrade_to_prepaid' when messages.message_type = 24 then 'essential_products_order_confirmation' else null end as message_type, messages.message_text from messages inner join users u on messages.recipient_id = u.id order by messages.created_at desc ) TO '/home/ubuntu/wms/public/messages.csv' WITH (FORMAT CSV, header, FORCE_QUOTE *)" 2>&1

SQL command is: PGPASSWORD=fam0usf0xy psql -h foxy-prod.crpdkkpcpspo.ap-south-1.rds.amazonaws.com -U foxy -d foxy_api_production -c "\COPY ( SELECT messages.id as message_id, messages.entity_type as "Order-Shipment", messages.entity_id as "Order-Shipment ID", messages.created_at, u.phone_number as recipient_phone_number, case when messages.channel = 0 then 'sms' when messages.channel = 1 then 'whatsapp' when messages.channel = 2 then 'voicecall' else null end as channel, case when messages.message_type = 0 then 'order_confirmation_with_surprise' when messages.message_type = 1 then 'order_confirmation_without_surprise' when messages.message_type = 2 then 'only_shipment_with_surprise_dispatched' when messages.message_type = 3 then 'only_shipment_without_surprise_dispatched' when messages.message_type = 4 then 'partial_shipment_with_surprise_dispatched' when messages.message_type = 5 then 'partial_shipment_without_surprise_dispatched' when messages.message_type = 6 then 'out_for_delivery' when messages.message_type = 7 then 'shipment_delivery_single_with_surprise' when messages.message_type = 8 then 'shipment_delivery_single_without_surprise' when messages.message_type = 9 then 'shipment_delivery_multiple_with_surprise' when messages.message_type = 10 then 'shipment_delivery_multiple_without_surprise' when messages.message_type = 11 then 'order_dispatch_delay' when messages.message_type = 12 then 'order_delivery_delay' when messages.message_type = 13 then 'order_watch_videos' when messages.message_type = 14 then 'order_item_cancellation_support' when messages.message_type = 15 then 'order_cancellation_customer' when messages.message_type = 16 then 'payment_refund' when messages.message_type = 17 then 'delayed_shipment_delivery' when messages.message_type = 18 then 'delayed_shipment_delivery_last' when messages.message_type = 19 then 'early_delivery' when messages.message_type = 20 then 'bag_abandon' when messages.message_type = 21 then 'order_payment_failure' when messages.message_type = 22 then 'welcome_message' when messages.message_type = 23 then 'order_confirmation_with_surprise_upgrade_to_prepaid' when messages.message_type = 24 then 'essential_products_order_confirmation' else null end as message_type, messages.message_text from messages inner join users u on messages.recipient_id = u.id order by messages.created_at desc ) TO '/home/ubuntu/wms/public/messages.csv' WITH (FORMAT CSV, header, FORCE_QUOTE *)" 2>&1
